### ISSUE TITLE
Data Nodes do not start when trying to start cluster on Ubuntu 18.04

### ISSUE THREAD

**Issue by ShilovSetCorp** [F21/hadoop#4]
Hello! When I am trying to start hadoop docker image with docker-compose up, everything starts perfect apart from datanodes. A get this logs: 

dn1    | STARTUP_MSG:   build = https://git-wip-us.apache.org/repos/asf/hadoop.git -r 66c47f2a01ad9637879e95f80c41f798373828fb; compiled by 'jdu' on 2017-10-19T20:39Z
dn1    | STARTUP_MSG:   java = 1.8.0_131
dn1    | ************************************************************/
dn1    | 19/07/29 06:36:01 INFO datanode.DataNode: registered UNIX signal handlers for [TERM, HUP, INT]
dn1    | 19/07/29 06:36:02 INFO impl.MetricsConfig: loaded properties from hadoop-metrics2.properties
dn1    | 19/07/29 06:36:02 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
dn1    | 19/07/29 06:36:02 INFO impl.MetricsSystemImpl: DataNode metrics system started
dn1    | 19/07/29 06:36:02 INFO datanode.BlockScanner: Initialized block scanner with targetBytesPerSec 1048576
dn1    | 19/07/29 06:36:02 INFO datanode.DataNode: Configured hostname is dn1
dn1    | 19/07/29 06:36:02 INFO datanode.DataNode: Starting DataNode with maxLockedMemory = 0
dn1    | 19/07/29 06:36:02 INFO datanode.DataNode: Opened streaming server at /0.0.0.0:50010
dn1    | 19/07/29 06:36:02 INFO datanode.DataNode: Balancing bandwith is 10485760 bytes/s
dn1    | 19/07/29 06:36:02 INFO datanode.DataNode: Number threads for balancing is 50
dn1    | #
dn1    | # A fatal error has been detected by the Java Runtime Environment:
dn1    | #
dn1    | #  SIGSEGV (0xb) at pc=0x00000000000060d6, pid=1, tid=0x00007f32e4e86ae8
dn1    | #
dn1    | # JRE version: OpenJDK Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
dn1    | # Java VM: OpenJDK 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
dn1    | # Derivative: IcedTea 3.4.0
dn1    | # Distribution: Custom build (Fri Jun 16 13:41:54 GMT 2017)
dn1    | # Problematic frame:
dn1    | # C  0x00000000000060d6
dn1    | #
dn1    | # Core dump written. Default location: //core or core.1
dn1    | #
dn1    | # An error report file with more information is saved as:
dn1    | # /tmp/hs_err_pid1.log
dn1    | #
dn1    | # If you would like to submit a bug report, please include
dn1    | # instructions on how to reproduce the bug and visit:
dn1    | #   http://icedtea.classpath.org/bugzilla
dn1    | #
....
dn1 exited with code 139

Would you be so kind to give some advice, what I could try to do in this situation?

**Comment by F21** [comment]
It's been a while since I used this image and the version of hadoop is pretty old. I did recall needing a lot of memory to run the different nodes. How much memory do you have in your machine?

**Comment by ShilovSetCorp** [comment]
> It's been a while since I used this image and the version of hadoop is pretty old. I did recall needing a lot of memory to run the different nodes. How much memory do you have in your machine?

Thamk you for so immediate answer! I use Virtual Box image for Ubuntu with 200 Gb of hdd and 8 Gb of RAM

**Comment by F21** [comment]
I recall having issues running all the nodes on a machine with 12GB RAM. I was able to get it working on a machine with 32GB of RAM. I'd suggest seeing if you can get access to a machine with more memory.

**Comment by ShilovSetCorp** [comment]
> I recall having issues running all the nodes on a machine with 12GB RAM. I was able to get it working on a machine with 32GB of RAM. I'd suggest seeing if you can get access to a machine with more memory.

Thank you!

**Comment by F21** [comment]
I just  tried `docker-compose up` on a machine with 32GB RAM and the datanode doesn't start either. I think it's possible the OpenJDK image is too old and won't work correctly with the latest version of docker. I think you can try building your own image using the latest stable by updating this line to `2.9.2`: https://github.com/F21/hadoop/blob/master/Dockerfile#L4

I don't have time to investigate this at the moment, but it's worth giving it a shot.
